spring:
  Datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    public-endpoint:  /auth/**, /auth

jwt:
  signerKey: "JeouJP21uUaI7ZS3qVFB7/NkRmmyyZo+Y+GdKMGqP/aOEFhkcyC7GGpyz33TmGER"